services:
  auth-api:
    build: ./backend/auth-api
    env_file: ./backend/auth-api/.env
    ports:
      - "8081:8080"
    depends_on:
      - redis
    environment:
      REDIS_URL: redis://redis:6379  

  user-api:
    build: ./backend/user-api
    env_file: ./backend/user-api/.env
    ports:
      - "8082:8080"
    depends_on:
      - mysql
    environment:
      DB_URL: jdbc:mysql://mysql:3306/userdb
      DB_USER: user
      DB_PASS: pass

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: userdb
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"
