services:
  auth-api:
    build: ./backend/auth-api
    env_file: ./backend/auth-api/.env
    ports:
      - "8081:8080"

  user-api:
    build: ./backend/user-api
    env_file: ./backend/user-api/.env
    ports:
      - "8082:8080"
